Repository nextcloud-libraries/nextcloud-upload, pull requests merged in 2022-06, with the labels that each got.

#8 Add basic UI
  lib/index.ts
  lib/upload.ts
  lib/uploader.ts
  package-lock.json
  package.json
  rollup.config.js
  src/UploadPicker.js
  src/UploadPicker.vue
  tsconfig.json
Labels: 4. to release

#144 Animate progress show/hide
  src/UploadPicker.vue
Labels: 3. to review

#426 Testing init
  .github/workflows/node-test.yml
  .gitignore
  __mocks__/axios.js
  __mocks__/fs.js
  __mocks__/readStream.js
  jest.config.js
  lib/upload.ts
  lib/uploader.ts
  lib/utils/config.ts
  lib/utils/upload.ts
  package-lock.json
  package.json
  tests/tsconfig.json
  tests/utils/config.spec.ts
  tests/utils/upload.spec.ts
  tsconfig.json
Labels: 4. to release

#429 Add Upload testing
  .github/workflows/node-test.yml
  .gitignore
  __tests__/upload.spec.ts
  jest.config.js
  lib/upload.ts
  package.json
Labels: 4. to release

#430 Fix upload syntax & lint fixes
  .github/workflows/node-test.yml
  lib/index.ts
  lib/upload.ts
  lib/uploader.ts
  lib/utils/config.ts
  lib/utils/upload.ts
Labels: 3. to review, technical debt

#431 Improve UploadData testing
  __mocks__/@nextcloud/axios.js
  __mocks__/@nextcloud/axios.ts
  __tests__/utils/upload.spec.ts
Labels: 4. to release

#432 Improve ts usage in l10n.ts
  lib/components/UploadPicker.vue
  lib/utils/l10n.ts
Labels: 3. to review, technical debt

#434 Update time estimates wordings
  build/extract-l10n.js
  l10n/messages.pot
  lib/components/UploadPicker.vue
Labels: 4. to release

#446 Init cypress upload testing
  .eslintrc.js
  .github/workflows/cypress.yml
  cypress.config.ts
  cypress/support/commands.js
  cypress/support/component-index.html
  cypress/support/component.js
  cypress/videos/UploadPicker.cy.js.mp4
  lib/components/UploadPicker.cy.js
  lib/components/UploadPicker.vue
  lib/index.ts
  lib/uploader.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement, 3. to review

#452 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#451 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#460 Improve eslint and cypress config
  .eslintignore
  .eslintrc.js
  .github/workflows/cypress.yml
  cypress/support/commands.js
  cypress/support/component-index.html
  package-lock.json
  package.json
Labels: enhancement, 4. to release
