Repository nextcloud-libraries/nextcloud-upload, pull requests merged in 2022-08, with the labels that each got.

#525 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#529 Update npm and node engines versions
  package.json
Labels: dependencies

#566 Allow to specify the destination on the UploadPicker component
  .gitignore
  cypress/support/component.ts
  cypress/videos/UploadPicker.cy.ts.mp4
  lib/components/UploadPicker.cy.ts
  lib/components/UploadPicker.vue
  lib/uploader.ts
Labels: enhancement, 3. to review

#567 Fix default progress bar size
  lib/components/UploadPicker.vue
Labels: 3. to review
