Repository nextcloud-libraries/nextcloud-upload, pull requests merged in 2023-12, with the labels that each got.

#988 v1.0.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#996 fix(uploader): encode destination
  lib/upload.ts
  lib/uploader.ts
  package-lock.json
  package.json
Labels: bug, 3. to review

#1000 fix(UploadPicker): Add label for upload progress and connect progress with description [a11y]
  l10n/messages.pot
  lib/components/UploadPicker.vue
Labels: bug, 3. to review

#1004 1.0.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#999 Migrate cypress config to use to vite
  cypress.config.ts
  cypress/components/ConflictPicker.cy.ts
  cypress/components/UploadPicker.cy.ts
  cypress/tsconfig.json
  lib/components/UploadPicker.vue
  lib/uploader.ts
  package-lock.json
  package.json
  tsconfig.json
  vite.config.ts
Labels: 3. to review, technical debt
