Repository nextcloud-libraries/nextcloud-upload, pull requests merged in 2023-10, with the labels that each got.

#942 fix: iconClass render
  lib/components/UploadPicker.vue
  lib/uploader.ts
Labels: 3. to review

#935 Set proper headers in upload requests
  lib/uploader.ts
  lib/utils/upload.ts
Labels: enhancement, 3. to review

#946 Divide lastModified by 1000 to have seconds
  lib/uploader.ts
Labels: bug, 3. to review

#950 Bump to v1.0.0-beta.19
  package.json
Labels: 3. to review
