Repository nextcloud-libraries/nextcloud-upload, pull requests merged in 2023-11, with the labels that each got.

#949 fix: always show menu label
  cypress/components/UploadPicker.cy.ts
  lib/components/UploadPicker.vue
Labels: regression, 4. to release, design

#952 1.0.0
  package-lock.json
  package.json
Labels: dependencies, 3. to review

#953 fix(upload): attach response to failed uploads too
  lib/uploader.ts
Labels: bug, 3. to review

#955 fix: Do not block if the filetype is unknown to the browser
  __tests__/utils/upload.spec.ts
  lib/utils/upload.ts
Labels: bug, 3. to review

#957 Fix "Add" label to "New"
  cypress/components/UploadPicker.cy.ts
  l10n/messages.pot
  lib/components/UploadPicker.vue
Labels: regression, 3. to review, design

#956 1.0.1
  .github/workflows/changelog-generate.yml
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#969 enable dependabot
  .github/dependabot.yml
Labels: dependencies, 3. to review

#979 v1.0.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
