Repository nextcloud-libraries/nextcloud-upload, pull requests merged in 2024-01, with the labels that each got.

#1038 fix: also add `X-OC-Mtime` header to final chunks move
  lib/uploader.ts
Labels: bug, 3. to review

#1042 fix: properly handle chunk upload failure
  lib/uploader.ts
Labels: bug, 3. to review, technical debt

#1021 chore: update workflows from templates
  .github/workflows/documentation.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/npm-publish.yml
Labels: dependencies, 3. to review, automated
