Repository nextcloud-libraries/nextcloud-upload, pull requests merged in 2024-09, with the labels that each got.

#1367 chore: also run node on main push
  .github/workflows/node-when-unrelated.yml
  .github/workflows/node.yml
Labels: 3. to review

#1366 feat(uploader): Allow to specify custom headers
  __tests__/uploader.spec.ts
  __tests__/utils/uploader.spec.ts
  lib/uploader.ts
  lib/utils/upload.ts
Labels: enhancement, 3. to review

#1368 fix(Uploader): The mtime should be a valid UNIX timestamp
  lib/uploader.ts
Labels: bug, 3. to review

#1369 fix(uploader): validation of the destination should not compare the class
  lib/uploader.ts
Labels: bug, 3. to review

#1372 fix(UploadPicker): Show menu if folders are enabled
  cypress/components/UploadPicker/UploadPicker.cy.ts
  cypress/components/UploadPicker/new-menu.cy.ts
  lib/components/UploadPicker.vue
Labels: bug, 3. to review

#1373 feat(UploadPicker): Allow to disable the "new"-menu
  cypress/components/UploadPicker/new-menu.cy.ts
  l10n/messages.pot
  lib/components/UploadPicker.vue
Labels: enhancement, 3. to review

#1370 fix: Make the default uploader global
  lib/index.ts
  lib/window.d.ts
Labels: bug, 3. to review

#1375 chore: Prepare v1.6.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1421 fix(l10n): Add proper config to align languages with Nextcloud language tags
  l10n/bg.pot
  l10n/cs.pot
  l10n/fi.pot
  l10n/hu.pot
  l10n/ja.pot
  l10n/nb.pot
  l10n/sk.pot
  l10n/th.pot
  transifex.yml
Labels: bug, 3. to review

#1422 chore: Release v1.6.1
  .github/dependabot.yml
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
