Repository nextcloud-libraries/nextcloud-upload, pull requests merged in 2024-06, with the labels that each got.

#1225 feat: Implement upload on public shares using dav endpoint v2
  __tests__/utils/uploader.spec.ts
  lib/uploader.ts
  vitest.config.ts
Labels: enhancement, 3. to review

#1224 refactor: Only import from nextcloud-axios not axios directly
  __tests__/utils/uploader.spec.ts
  lib/uploader.ts
  package-lock.json
  package.json
  vitest.config.ts
Labels: 3. to review

#1229 chore: Prepare v1.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1234 fix: Adjust `isPublic` detection for uploader
  lib/index.ts
Labels: bug, 3. to review

#1233 Added retry capability for uploading files
  __tests__/utils/upload.spec.ts
  cypress.config.ts
  lib/uploader.ts
  lib/utils/upload.ts
  package-lock.json
  package.json
Labels: enhancement, 3. to review

#1244 refactor: Use `getUniqueName` from `@nextcloud/files`
  lib/components/ConflictPicker.vue
  lib/components/UploadPicker.vue
  lib/utils/uniqueName.ts
  package-lock.json
  package.json
Labels: 3. to review

#1245 refactor: Use public-share aware functions from `@nextcloud/files` and `@nextcloud/sharing`
  __tests__/utils/uploader.spec.ts
  cypress/components/UploadPicker.cy.ts
  lib/index.ts
  lib/uploader.ts
  package-lock.json
  package.json
Labels: 3. to review

#1249 chore: Prepare v1.4.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1251 chore: Prepare 1.4.1 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1256 fix(uploader): increase max concurrency to 5
  lib/uploader.ts
Labels: enhancement, 3. to review, performances
