Repository nextcloud-libraries/nextcloud-upload, pull requests merged in 2024-04, with the labels that each got.

#1131 feat: allow to specify the root of an upload
  lib/uploader.ts
Labels: 3. to review, technical debt

#1132 feat: allow to specify forbidden characters
  cypress/components/UploadPicker.cy.ts
  cypress/cypress.d.ts
  cypress/support/commands.ts
  cypress/tsconfig.json
  lib/components/ConflictPicker.vue
  lib/components/UploadPicker.vue
Labels: enhancement, 3. to review

#1133 v1.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1155 fix: Drop dependency on moment.js
  lib/components/NodesPicker.vue
  package-lock.json
  package.json
Labels: bug, 3. to review

#1153 fix(upload): Do not read chunks into memory but just stream file chunks
  lib/utils/upload.ts
  package-lock.json
  package.json
Labels: bug, 3. to review

#1156 chore: Prepare 1.1.1 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1166 feat(ConflictPicker): Allow to use `FileSystemEntry`
  lib/components/ConflictPicker.vue
  lib/index.ts
Labels: enhancement, 3. to review

#1171 fix(ConflictPicker): Ensure component works also if browser does not support FileSystemEntry
  lib/components/ConflictPicker.vue
  lib/components/NodesPicker.vue
  lib/utils/filesystem.ts
Labels: bug, 3. to review

#1173 fix: Refactor logger and fix badges in README
  README.md
  __tests__/tsconfig.json
  __tests__/utils/logger.spec.ts
  lib/utils/logger.ts
  package-lock.json
  package.json
  tsconfig.json
  vitest.config.ts
Labels: bug, 3. to review

#1174 fix(tests): Add tests for filesystem helpers
  __tests__/utils/filesystem.spec.ts
  lib/utils/filesystem.ts
Labels: bug, 3. to review
