Repository nextcloud-libraries/nextcloud-upload, pull requests merged in 2024-05, with the labels that each got.

#1175 feat: Allow to upload directories and allow bulk upload
  __tests__/setup.ts
  __tests__/utils/fileTree.spec.ts
  cypress/components/UploadPicker.cy.ts
  l10n/messages.pot
  lib/components/ConflictPicker.vue
  lib/components/UploadPicker.vue
  lib/index.ts
  lib/uploader.ts
  lib/utils/fileTree.ts
  lib/utils/uniqueName.ts
  package-lock.json
  package.json
  vitest.config.ts
Labels: enhancement, 3. to review

#1207 fix(docs): Add parameter docs for `getUploader`
  lib/index.ts
Labels: bug, 3. to review

#1206 feat: Split new-menu entries into `upload` `new` and *other*
  lib/components/UploadPicker.vue
  package-lock.json
  package.json
Labels: enhancement, 3. to review

#1214 feat(ConflictPicker): refresh preview on etag change
  lib/components/NodesPicker.vue
Labels: enhancement, 3. to review, papercut, design

#1217 chore: Prepare v1.2.0 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
