Repository nextcloud-libraries/nextcloud-upload, pull requests merged in 2025-02, with the labels that each got.

#1601 chore: include vue devtools in dev build
  .env.development
  REUSE.toml
Labels: 3. to review

#1602 test: silence console output when testing logger
  __tests__/utils/logger.spec.ts
Labels: 3. to review

#1603 fix(uploader): Correctly (re)set progress on upload
  __tests__/utils/upload.spec.ts
  cypress/components/UploadPicker/progress.cy.ts
  lib/components/UploadPicker.vue
  lib/uploader.ts
  lib/utils/upload.ts
Labels: bug, 3. to review

#1518 fix: fix eslint scripts
  __mocks__/@nextcloud/axios.ts
  __tests__/upload.spec.ts
  __tests__/utils/config.spec.ts
  cypress/components/UploadPicker/invalid-filenames.cy.ts
  lib/utils/config.ts
  lib/utils/filesystem.ts
  package.json
Labels: 3. to review

#1613 ci: update workflows
  .github/workflows/changelog-generate.yml
  .github/workflows/cypress.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/documentation.yml
  .github/workflows/l10n.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/npm-publish.yml
  .github/workflows/reuse.yml
Labels: 3. to review

#1606 feat(UploadPicker): Allow to set color to primary
  lib/components/UploadPicker.vue
Labels: enhancement, 3. to review

#1615 fix: include non conflicting files for upload
  __tests__/utils/conflicts-handler.spec.ts
  cypress/components/ConflictPicker.cy.ts
  lib/utils/conflicts.ts
Labels: bug, 3. to review

#1617 fix(uploader): properly propagate upload cancelled status
  cypress/components/UploadPicker/cancel.cy.ts
  l10n/messages.pot
  lib/components/UploadPicker.vue
  lib/errors/UploadCancelledError.ts
  lib/uploader.ts
Labels: bug, 3. to review

#1530 feat: add assembling status to UploadPicker
  cypress/components/UploadPicker/UploadPicker.cy.ts
  cypress/components/UploadPicker/progress.cy.ts
  cypress/components/UploadPicker/status.cy.ts
  cypress/support/component.ts
  l10n/messages.pot
  lib/components/UploadPicker.vue
  lib/uploader.ts
Labels: enhancement, 3. to review

#1635 fix(conflictpicker): force background on sticky header
  lib/components/ConflictPicker.vue
Labels: bug, 3. to review, design
