Repository nextcloud-libraries/nextcloud-upload, pull requests merged in 2025-03, with the labels that each got.

#1627 feat(uploader): add ETA implementation with upload speed information
  cypress/components/UploadPicker/UploadPicker.cy.ts
  cypress/components/UploadPicker/invalid-filenames.cy.ts
  cypress/components/UploadPicker/progress.cy.ts
  cypress/cypress.d.ts
  cypress/support/commands.ts
  lib/components/UploadPicker.vue
  lib/index.ts
  lib/uploader/eta.spec.ts
  lib/uploader/eta.ts
  lib/uploader/index.ts
  lib/uploader/uploader.ts
  package-lock.json
  package.json
Labels: enhancement, 3. to review

#1642 chore: 1.9.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1657 fix(upload): do not retry when insufficient storage but when locked
  __tests__/utils/upload.spec.ts
  cypress/components/UploadPicker/retry.cy.ts
  lib/utils/upload.ts
Labels: bug, 3. to review

#1666 fix(uploader): only set mtime if valid value is passed
  lib/uploader/uploader.ts
Labels: bug, 3. to review

#1667 chore: prepare release of v1.9.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1672 chore(i18n): Improved grammar
  l10n/messages.pot
  lib/uploader/uploader.ts
Labels: bug, 3. to review
